name: Android CI

on:
  push:
    branches: ["gen-apk"]
  pull_request:
    branches: ["gen-apk"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Submodule
        run: |
          git submodule update --init --recursive

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # 指定 pnpm 版本
          run_install: false # 不自动安装依赖（你可以后面手动控制）

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          curl -fsSL https://get.pnpm.io/install.sh | sh -

      - name: Grant execute permission for gradlew
        run: chmod +x ./WebApkShell/gradlew

      - name: Install Dependency
        run: bun i

      - name: Build with Gradle
        run: |
          cp WebApkShell/genApk.ts .
          bun genApk.ts

      - name: Generate version with timestamp
        id: gen_tag
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M)
          CUSTOM_TAG="v${TIMESTAMP}"
          echo "custom_tag=${CUSTOM_TAG}" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_version: ${{ steps.gen_tag.outputs.custom_tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            WebApkShell/app/build/outputs/apk/release/*.apk
          tag_name: ${{ steps.gen_tag.outputs.custom_tag }}   # ← 必须和上面一致
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
